#---------------------------
# Material-T
# Author: invom
# Github: https://github.com/invom/Material-T
#---------------------------

#---------------------------
# 全局
# Site
#---------------------------
favicon: https://github.com/NieLamu/NieLamu.github.io/raw/develop/statics/img/favicon.ico
apple_touch_icon: https://github.com/NieLamu/NieLamu.github.io/raw/develop/statics/img/favicon.png


#---------------------------
# 首页
# Index Page
#---------------------------
index: 
  banner_img: https://images.unsplash.com/photo-1549932967-c60dce5958ce?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80
  # available: 0 - 100
  banner_img_height: 100
  subtitle:
    enable: true
  auto_excerpt:
    enable: true
    length: 175
  # available: _blank | _self
  post_url_target: _self
  post_info:
    enable: true


#---------------------------
# 导航栏
# Head Navbar
#---------------------------
navbar:
  menu:
    enable: true
    list:
      archives: /archives/
      about: /about/
  icons:
    enable: true
    list: 
      github: 
        url: https://github.com/NieLamu
        tips: 'Codes Page'
      instagram: 
        url: https://www.instagram.com/simadao/
        tips: 'instagram'
      twitter: 
        url: https://twitter.com/mxmxlty2010
        tips: 'twitter'
      facebook: 
        url: https://www.facebook.com/nielamu
        tips: 'facebook'

#---------------------------
# 文章页
# Post Page
#---------------------------
post: 
  banner_img: /img/post-banner.jpg
  # available: 0 - 100
  banner_img_height: 100
  # available: 1 | 2
  layout: 1
  toc: 
    enable: true
  # Code Highlight Theme available: github | tomorrow | tomorrow-night | tomorrow-night-eighties
  highlight:
    enable: true
    theme: tomorrow-night-eighties
  comments: 
    enable: true
    type: disqus

disqus:
  shortname: nielamu

# Valine
# You can get your appid and appkey from https://leancloud.cn
# More info available at https://valine.js.org
valine:
  enable: false # When enable is set to be true, leancloud_visitors is recommended to be closed for the re-initialization problem within different leancloud adk version.
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier, See: https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: 说点什么 # comment box placeholder
  avatar: retro # gravatar style https://valine.js.org/avatar.html
  pageSize: 10 # pagination size
  visitor: false # leancloud-counter-security is not supported for now. When visitor is set to be true, appid and appkey are recommended to be the same as leancloud_visitors' for counter compatibility. Article reading statistic https://valine.js.org/visitor.html


#---------------------------
# 归档页
# Archive Page
#---------------------------
archive: 
  banner_img: https://images.unsplash.com/photo-1549945689-8b0758325042?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80
  # available: 0 - 100
  banner_img_height: 100

#---------------------------
# 关于页
# About Page
#---------------------------
about:
  banner_img: https://images.unsplash.com/photo-1549937263-318fad9e0f59?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80
  # available: 0 - 100
  banner_img_height: 100
  avatar: https://github.com/NieLamu/NieLamu.github.io/raw/develop/statics/img/avatar.jpg
  name: NieLamu
  job: A coder
  introduce: 
  extension: <b>はじめまして ^_^</b>
  icons:
    


#---------------------------
# 底部信息
# Footer
#---------------------------
issue: <a href="https://github.com/NieLamu/NieLamu.github.io/" class="btn" target="_blank">Fork Me</a><a href="https://github.com/NieLamu/NieLamu.github.io/issues" class="btn" target="_blank">Report an issue</a>
footer: <b>Drink plenty of hot water and try to restart.</b>
