#---------------------------
# Material-T
# Author: invom
# Github: https://github.com/invom/Material-T
#---------------------------

#---------------------------
# 全局
# Site
#---------------------------
favicon: /img/favicon.ico
apple_touch_icon: /img/favicon.png

main_color: '#00bcd4'


#---------------------------
# 首页
# Index Page
#---------------------------
index: 
  banner_img: /img/index.png
  subtitle:
    enable: true
  auto_excerpt:
    enable: true
    length: 175
  # available: _blank | _self
  post_url_target: _self
  post_info:
    enable: true


#---------------------------
# 导航栏
# Head Navbar
#---------------------------
navbar:
  menu:
    enable: true
    list:
      archives: /archives/
      about: /about/
  icons:
    enable: true
    list: 
      github: 
        url: https://github.com/NieLamu
        tips: 'Codes Page'
      instagram: 
        url: https://www.instagram.com/simadao/
      twitter: 
        url: https://twitter.com/mxmxlty2010
      facebook: 
        url: https://www.facebook.com/nielamu

#---------------------------
# 文章页
# Post Page
#---------------------------
post: 
  toc: 
    enable: true
  comments: 
    enable: false
    type: disqus

disqus:
  shortname: nielamu

# Valine
# You can get your appid and appkey from https://leancloud.cn
# More info available at https://valine.js.org
valine:
  enable: false # When enable is set to be true, leancloud_visitors is recommended to be closed for the re-initialization problem within different leancloud adk version.
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier, See: https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Say something # comment box placeholder
  avatar: retro # gravatar style https://valine.js.org/avatar.html
  pageSize: 10 # pagination size
  visitor: false # leancloud-counter-security is not supported for now. When visitor is set to be true, appid and appkey are recommended to be the same as leancloud_visitors' for counter compatibility. Article reading statistic https://valine.js.org/visitor.html


#---------------------------
# 归档页
# Archive Page
#---------------------------
archive: 
  banner_img: /img/index.png

#---------------------------
# 关于页
# About Page
#---------------------------
about:
  banner_img: https://source.unsplash.com/user/nielamu/likes/
  avatar:
    url: /img/avatar.jpg
    desc: NOT ME
  name: NieLamu
  job: A coder
  introduce: 
  extension: <b>はじめまして ^_^</b>
  icons:
    enable: true
    


#---------------------------
# 底部信息
# Footer
#---------------------------
footer: <a href="https://github.com/NieLamu/NieLamu.github.io/issues" class="btn" target="_blank">Report an issue</a>